In [19]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from joblib import dump, load


In [20]:
X, y = load_iris(return_X_y=True)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)

In [23]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)
clf = SVC()
clf.fit(X, y)

SVC()

In [30]:
dump(gnb, 'iris.pkl') 

['iris.pkl']

In [31]:
load('iris.pkl')

GaussianNB()

In [18]:
y_pred = model.predict(X_test)

In [16]:
print("Number of mislabeled points out of a total %d points : %d" % (X_test.shape[0], (y_test != y_pred).sum()))

Number of mislabeled points out of a total 75 points : 4


In [17]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
data = load_iris()
[data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [10]:
s = ['sepal_length',
'sepal_width',
'petal_length',
'petal_width']

In [1]:
!pip install fastparquet

     |████████████████████████████████| 1.5 MB 7.4 MB/s eta 0:00:01
     |████████████████████████████████| 1.6 MB 40.7 MB/s eta 0:00:01


[sudo] password for theo: 


In [11]:
from pycaret.datasets import get_data
juice = get_data('juice')
from pycaret.classification import *
exp_name = setup(data = juice,  target = 'Purchase')
lr = create_model('lr')
create_api(lr, 'lr_api')


API sucessfully created. This function only creates a POST API, it doesn't run it automatically.

To run your API, please run this command --> !python lr_api.py
    


In [10]:
!pip install uvicorn

     |████████████████████████████████| 52 kB 1.7 MB/s eta 0:00:011
     |████████████████████████████████| 58 kB 7.7 MB/s  eta 0:00:01


In [12]:
create_docker('lr_api')

Writing requirements.txt
Writing Dockerfile
Dockerfile and requirements.txt successfully created.
To build image you have to run --> !docker image build -f "Dockerfile" -t IMAGE_NAME:IMAGE_TAG .
        


In [14]:
!docker image build -f "Dockerfile" -t lrapi:1.0 .

Sending build context to Docker daemon  110.6kB
Step 1/7 : FROM python:3.8-slim
3.8-slim: Pulling from library/python

b503b376: Pulling fs layer 
ac0246d0: Pulling fs layer 
e345656c: Pulling fs layer 
ff7766ad: Pulling fs layer 
Digest: sha256:a43e1e26c4fbbe9b5d983533c094547d67f0325148f27dd85a0f8b7f0aced23e[5A
Status: Downloaded newer image for python:3.8-slim
 ---> 920c743c9ca8
Step 2/7 : WORKDIR /app
 ---> Running in e1bb286487a2
Removing intermediate container e1bb286487a2
 ---> 65fa749b79c2
Step 3/7 : ADD . /app
 ---> e45cdc4071cd
Step 4/7 : RUN apt-get update && apt-get install -y libgomp1
 ---> Running in 83debb33a6b1
Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
Get:4 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [116 kB]
Get:5 http://deb.debian.org/debian bullseye/main

  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=67918 sha256=0c2bc32344a7b48857443065fc93ce762a21d303133da5f3d8c2c1032db66bb1
  Stored in directory: /root/.cache/pip/wheels/6b/76/62/6da97734911ffcbdd559fd1a3f28526321f0ae699182a23866
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27098 sha256=511b658838810a3e23a483f52d39575c3ec37644be5eefe7ad08eb059d4e86e0
  Stored in directory: /root/.cache/pip/wheels/23/14/6e/4be5bfeeb027f4939a01764b48edd5996acf574b0913fe5243
  Created wheel for imagehash: filename=ImageHash-4.2.1-py

Removing intermediate container 24f196a96c49
 ---> 660d488f431f
Step 6/7 : EXPOSE 8000
 ---> Running in 4ffdb683eb71
Removing intermediate container 4ffdb683eb71
 ---> 87567e617fcc
Step 7/7 : CMD ["python", "lr_api.py"]
 ---> Running in cd4475b62ae6
Removing intermediate container cd4475b62ae6
 ---> 787d498fda08
Successfully built 787d498fda08
Successfully tagged lrapi:1.0


In [60]:
from pydantic import BaseModel, validator
class PredInput(BaseModel):
    sepal_length: float
    sepal_width: float
    petal_length: float
    petal_width: float


        

In [62]:
p = PredInput(sepal_length=1, petal_length=1, sepal_width=2, petal_width=3)

In [51]:
import pandas as pd
pd.DataFrame(p.__dict__)

ValueError: If using all scalar values, you must pass an index

In [56]:
import numpy as np

In [58]:
clf.predict(np.array([1,2,3,4]).reshape(1,4))

array([2])

In [63]:
np.array([p.sepal_length, p.sepal_width, p.petal_length, p.petal_width])

array([1., 2., 1., 3.])